[build-system]
requires = ["scikit-build-core",
            "numpy>=2"]
build-backend = "scikit_build_core.build"

[project]
name = "rmsh"
dependencies=["numpy>=1.4"]
version = "0.0.1"

[tool.scikit-build]
wheel.py-api = "cp37"
