[build-system]
requires = ["scikit-build-core[rich,pyproject]"]
build-backend = "scikit_build_core.build"

[project]
name = "rmsh"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "ninja"
]